dist: trusty
sudo: required

services:
  - docker

language: scala

jobs:
  include:
    - stage: docker - build test image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t sbt-example:test -f Dockerfile.test .
      - docker run sbt-example:test
    - stage: docker - build release image
      script:
      - docker build -t sbt-example .
      - docker images
      - docker tag sbt-example $DOCKER_USERNAME/sbt-example

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    fi
  - docker push $DOCKER_USERNAME/sbt-example
