dist: trusty
sudo: required
services:
- docker
language: scala
before_install:
- openssl aes-256-cbc -K $encrypted_994f1ea3f6dd_key -iv $encrypted_994f1ea3f6dd_iv
  -in id_rsa.enc -out $HOME/.ssh/id_rsa -d
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- wget  https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip
  -O /tmp/terraform.zip && sudo unzip  /tmp/terraform.zip -d /usr/local/bin/ && rm
  /tmp/terraform.zip
jobs:
  include:
  - stage: docker - build test image
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t sbt-example:test -f Dockerfile.test .
    - docker run sbt-example:test
  - stage: docker - build release image
    script:
    - docker build -t sbt-example:latest .
    - docker tag sbt-example $DOCKER_USERNAME/sbt-example:latest
    - docker images
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME"
      -p="$DOCKER_PASSWORD"; fi
    - docker tag sbt-example:latest $DOCKER_USERNAME/sbt-example:latest
    - docker push $DOCKER_USERNAME/sbt-example:latest
  - stage: test deployement on aws
    script:
    - cd terraform && terraform plan --out myplan.tfplan
    - cd terraform && terraform apply -auto-approve=true myplan.tfplan
    - cd terraform && terraform show myplan.tfplan
