- name: docker - launch sbt-example
  docker_container:
    name: sbt-example
    recreate: yes
    image: mikefaille/sbt-example
    state: started
    restart_policy: on-failure
    pull: true
    ports:
    - "8080:9000"
